services:
    trade.client.btc_markets:
        class: GetRepo\TradeBundle\Client\BTCMarketsClient
        arguments: ['@service_container']
    trade.data_collector.btc_markets:
        class: GetRepo\TradeBundle\DataCollector\BTCMarketsDataCollector
        arguments: ['@trade.client.btc_markets']